app = "apa-control-web"
primary_region = "gru"

[build]
  dockerfile = "apps/administrativo/Dockerfile"
  build-context = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

